spring:
  messages:
    basename: errors

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:file:/Users/woowatech11/Documents/subway
    username: sa
    password:
    driver-class-name: org.h2.Driver
